from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "docs" / "decisions"
README = DECISIONS / "README.md"

pattern = re.compile(r"adr:\s*(\d+).*?title:\s*(.+?)\n.*?status:\s*(.+?)\n", re.S | re.I)

records = []

for file in sorted(DECISIONS.glob("ADR_*.md")):
    text = file.read_text(encoding="utf-8")
    m = pattern.search(text)
    if not m:
        continue
    num, title, status = m.groups()
    records.append((int(num), title.strip(), status.strip(), file.name))

records.sort()

lines = [
"# Architecture Decisions",
"",
"> ⚠️ This file is automatically generated.",
"> Do not edit manually.",
"> Run `python tools/build_docs.py`.",
"",
"| ADR | Title | Status | File |",
"|---|---|---|---|"
]

for n,title,status,name in records:
    lines.append(f"| ADR_{n:04d} | {title} | {status.title()} | {name} |")

README.write_text("\n".join(lines), encoding="utf-8")
print(f"Updated {README}")
